### ISSUE TITLE
MatplotlibDeprecationWarning

### ISSUE THREAD

**Issue by pravirkr** [thepetabyteproject/your#47]
When running the plotting functions, this warning pops up:
```
MatplotlibDeprecationWarning: Support for setting the 'text.latex.preamble' or 
'pgf.preamble' rcParam to a list of strings is deprecated since 3.3 and will be
removed two minor releases later; set it to a single string instead.
    self[key] = other[key]

```
It would be good to fix this warning. I suppose putting all LaTex commands in a single string will do.
This issue is part of my JOSS review.

**Comment by devanshkv** [comment]
Fixed with bda807b4d4fb59b190b8271df6c3f02fd5479630.

**Comment by Haninu** [comment]
Hello, 

Please I have the same problem, how can i fix it ? Actually, I've a code which I did convert to .exe and it work perfectly on my computer but in my colleague's computer it doesn't, is that have any relation with Anaconda because for the coding i used Jupyter notebook, The error text content is :

matplotlibDeprecationWarning: Support for setting the 'text.latex.preamble' or 'pgf.preamble' rcParam to a list of strings is deprecated since 3.3 and will be removed two minor releases later; set it to a single string instead.

**Comment by devanshkv** [comment]
@Haninu this is just a warning, and should not affect the functionality of the package.

In case you fix it, please feel free to send a PR.
